name: Docker Image Push and Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 --push -t ${{ secrets.DOCKER_USERNAME }}/myfirstrepo:latest .

      - name: Log out from DockerHub
        run: docker logout

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}  # Replace with your EC2 instance's public IP or hostname
          username: ${{ secrets.SSH_USERNAME }}  # Replace with your SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add your private SSH key as a secret in your repository
          port: 22
          script: |
            docker stop my-container-name || true
            docker rm my-container-name || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/myfirstrepo:latest
            docker run -d --name my-container-name -p 80:80 ${{ secrets.DOCKER_USERNAME }}/myfirstrepo:latest

